import {
  Column,
  CreateDateColumn,
  DeleteDateColumn,
  Entity,
  Index,
  JoinColumn,
  ManyToOne,
  UpdateDateColumn,
} from 'typeorm';

import type {
  MessageDirection,
  MessageSenderType,
  MessageStatus,
  MessageType,
} from '../../../contracts/index';
import { UuidV7Entity } from '../../../lib/entities/uuid-v7.entity';
import { Company } from '../../company/entities/company.entity';
import { CompanyMember } from '../../company-members/entities/company-member.entity';
import { Customer } from '../../customers/entities/customer.entity';
import { MessageTemplate } from '../../channels/entities/message-template.entity';
import { Conversation } from '../../conversations/entities/conversation.entity';

@Entity('messages')
@Index(['conversationId', 'createdAt'])
@Index(['conversationId', 'externalId'], { unique: true })
@Index(['conversationId', 'clientMessageId'], { unique: true })
@Index(['companyId', 'createdAt'])
export class Message extends UuidV7Entity {
  @Column({ name: 'company_id', type: 'varchar', length: 36 })
  companyId: string;

  @ManyToOne(() => Company, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'company_id' })
  company: Company;

  @Column({ name: 'conversation_id', type: 'varchar', length: 36 })
  conversationId: string;

  @ManyToOne(() => Conversation, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'conversation_id' })
  conversation: Conversation;

  @Column({ type: 'varchar', length: 50 })
  direction: MessageDirection;

  @Column({ name: 'sender_type', type: 'varchar', length: 50 })
  senderType: MessageSenderType;

  @Column({ name: 'sender_member_id', type: 'varchar', length: 36, nullable: true })
  senderMemberId?: string | null;

  @ManyToOne(() => CompanyMember, { nullable: true, onDelete: 'SET NULL' })
  @JoinColumn({ name: 'sender_member_id' })
  senderMember?: CompanyMember | null;

  @Column({ name: 'sender_customer_id', type: 'varchar', length: 36, nullable: true })
  senderCustomerId?: string | null;

  @ManyToOne(() => Customer, { nullable: true, onDelete: 'SET NULL' })
  @JoinColumn({ name: 'sender_customer_id' })
  senderCustomer?: Customer | null;

  /** Temp id generated by the front for optimistic UI + idempotent retries. */
  @Column({ name: 'client_message_id', type: 'varchar', length: 64, nullable: true })
  clientMessageId?: string | null;

  @Column({ type: 'varchar', length: 50, default: 'text' })
  type: MessageType;

  @Column({ type: 'text', nullable: true })
  body?: string | null;

  @Column({ name: 'reply_to_message_id', type: 'varchar', length: 36, nullable: true })
  replyToMessageId?: string | null;

  @ManyToOne(() => Message, { nullable: true, onDelete: 'SET NULL' })
  @JoinColumn({ name: 'reply_to_message_id' })
  replyToMessage?: Message | null;

  @Column({ name: 'template_id', type: 'varchar', length: 36, nullable: true })
  templateId?: string | null;

  @ManyToOne(() => MessageTemplate, { nullable: true, onDelete: 'SET NULL' })
  @JoinColumn({ name: 'template_id' })
  template?: MessageTemplate | null;

  /** WA: wamid, stored raw as reported by the provider. */
  @Column({ name: 'external_id', type: 'varchar', length: 128, nullable: true })
  externalId?: string | null;

  @Column({ type: 'varchar', length: 50, default: 'pending' })
  status: MessageStatus;

  @Column({ name: 'status_updated_at', type: 'datetime', nullable: true })
  statusUpdatedAt?: Date;

  @Column({ name: 'error_code', type: 'varchar', length: 50, nullable: true })
  errorCode?: string | null;

  @Column({ name: 'error_message', type: 'varchar', length: 500, nullable: true })
  errorMessage?: string | null;

  @Column({ name: 'sent_at', type: 'datetime', nullable: true })
  sentAt?: Date;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;

  @DeleteDateColumn({ nullable: true })
  deletedAt?: Date;
}
