import { z } from 'zod';

/**
 * WhatsApp configuration contracts.
 *
 * Canonical field names live here (camelCase, matching the API entity):
 * `businessId`, `phoneNumberId`, `webhookUrl`, `webhookVerifyToken`,
 * `apiVersion`, `apiBaseUrl`, `isActive`.
 *
 * The frontend form may be stricter (min lengths, empty-string placeholders)
 * but it must never rename these fields again.
 */
export const WHATSAPP_API_VERSIONS = [
  'v18.0',
  'v19.0',
  'v20.0',
  'v21.0',
  'v22.0',
  'v23.0',
] as const;

export const WhatsAppApiVersionSchema = z.enum(WHATSAPP_API_VERSIONS);

export type WhatsAppApiVersion = z.infer<typeof WhatsAppApiVersionSchema>;

export const DEFAULT_WHATSAPP_API_VERSION: WhatsAppApiVersion = 'v22.0';

/**
 * Shape returned by `GET /integration/whatsapp/config`.
 * `businessId` is nullable in the database; webhook fields are always present
 * (the verify token is generated by the subscriber when missing).
 *
 * Only JSON-representable fields live here (no timestamps): this schema is also
 * used to serialize the endpoint (`@ZodSerializerDto`) and to generate the
 * OpenAPI document, where `Date` is not representable.
 */
export const WhatsAppConfigSchema = z.object({
  id: z.string(),
  apiVersion: WhatsAppApiVersionSchema,
  apiBaseUrl: z.string(),
  businessId: z.string().nullable(),
  accessToken: z.string(),
  phoneNumberId: z.string(),
  webhookUrl: z.string(),
  webhookVerifyToken: z.string(),
  isActive: z.boolean(),
});

export type WhatsAppConfigResponse = z.infer<typeof WhatsAppConfigSchema>;

/** Payload accepted by `POST /integration/whatsapp` and `PATCH /integration/whatsapp/config`. */
export const CreateWhatsAppConfigSchema = z.object({
  businessId: z.string(),
  accessToken: z.string(),
  phoneNumberId: z.string(),
  webhookUrl: z.string(),
  apiVersion: WhatsAppApiVersionSchema.optional(),
  apiBaseUrl: z.string().optional(),
  webhookVerifyToken: z.string().optional(),
});

export const UpdateWhatsAppConfigSchema = CreateWhatsAppConfigSchema.partial();

export type CreateWhatsAppConfigInput = z.infer<
  typeof CreateWhatsAppConfigSchema
>;
export type UpdateWhatsAppConfigInput = z.infer<
  typeof UpdateWhatsAppConfigSchema
>;
