import { MigrationInterface, QueryRunner } from "typeorm";

export class V2Baseline1791153602905 implements MigrationInterface {
    name = 'V2Baseline1791153602905'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` char(36) NOT NULL, \`email\` varchar(255) NOT NULL, \`username\` varchar(100) NOT NULL, \`password_hash\` varchar(255) NOT NULL, \`first_name\` varchar(100) NULL, \`last_name\` varchar(100) NULL, \`phone_number\` varchar(20) NULL, \`avatar_url\` varchar(512) NULL, \`is_platform_admin\` tinyint NOT NULL DEFAULT 0, \`last_login_at\` datetime NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`), UNIQUE INDEX \`IDX_fe0bb3f6520ee0469504521e71\` (\`username\`), UNIQUE INDEX \`IDX_17d1817f241f10a3dbafb169fd\` (\`phone_number\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`companies\` (\`id\` char(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`email\` varchar(255) NULL, \`phone_number\` varchar(20) NULL, \`address\` text NULL, \`timezone\` varchar(64) NOT NULL DEFAULT 'America/Lima', \`status\` varchar(50) NOT NULL DEFAULT 'active', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, UNIQUE INDEX \`IDX_d0af6f5866201d5cb424767744\` (\`email\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`company_members\` (\`id\` char(36) NOT NULL, \`company_id\` char(36) NOT NULL, \`user_id\` char(36) NOT NULL, \`role\` varchar(50) NOT NULL DEFAULT 'agent', \`status\` varchar(50) NOT NULL DEFAULT 'active', \`accepts_auto_assign\` tinyint NOT NULL DEFAULT 1, \`max_open_conversations\` int NULL, \`joined_at\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_7e141c8e7fcd537db28ec8d68d\` (\`company_id\`, \`role\`, \`status\`), UNIQUE INDEX \`IDX_6e865dcafa308a5a7825d8de5c\` (\`company_id\`, \`user_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`notifications\` (\`id\` char(36) NOT NULL, \`company_id\` char(36) NOT NULL, \`recipient_member_id\` char(36) NOT NULL, \`type\` varchar(50) NOT NULL, \`title\` varchar(255) NOT NULL, \`body\` text NULL, \`data\` json NULL, \`read_at\` datetime NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_5790f95902331e18e3a410d1db\` (\`recipient_member_id\`, \`read_at\`, \`created_at\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`pipeline_stages\` (\`id\` char(36) NOT NULL, \`company_id\` char(36) NOT NULL, \`name\` varchar(100) NOT NULL, \`position\` int NOT NULL, \`color\` varchar(7) NULL, \`is_won\` tinyint NOT NULL DEFAULT 0, \`is_lost\` tinyint NOT NULL DEFAULT 0, UNIQUE INDEX \`IDX_6d96531b70c35c80186dc8531c\` (\`company_id\`, \`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`customers\` (\`id\` char(36) NOT NULL, \`company_id\` char(36) NOT NULL, \`first_name\` varchar(100) NULL, \`last_name\` varchar(100) NULL, \`display_name\` varchar(200) NULL, \`email\` varchar(255) NULL, \`phone_number\` varchar(20) NULL, \`avatar_url\` varchar(512) NULL, \`source\` varchar(50) NOT NULL DEFAULT 'manual', \`pipeline_stage_id\` char(36) NULL, \`owner_member_id\` char(36) NULL, \`last_interaction_at\` datetime NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, INDEX \`IDX_9bf3490812e7d308b05f08cbd3\` (\`company_id\`, \`last_interaction_at\`), INDEX \`IDX_bce1c8e2cd87b249a640f87bbc\` (\`company_id\`, \`pipeline_stage_id\`), UNIQUE INDEX \`IDX_c7394e23cee3906898dc219c5c\` (\`company_id\`, \`phone_number\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`channels\` (\`id\` char(36) NOT NULL, \`company_id\` char(36) NOT NULL, \`type\` varchar(50) NOT NULL, \`name\` varchar(100) NOT NULL, \`external_account_id\` varchar(100) NOT NULL, \`display_address\` varchar(100) NULL, \`credentials\` text NOT NULL, \`settings\` json NULL, \`webhook_verify_token\` varchar(256) NULL, \`status\` varchar(50) NOT NULL DEFAULT 'active', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, INDEX \`IDX_17f217069468737f98e5ce9508\` (\`company_id\`, \`type\`), UNIQUE INDEX \`IDX_20b3662df2548b1a2a120db326\` (\`type\`, \`external_account_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`message_templates\` (\`id\` char(36) NOT NULL, \`company_id\` char(36) NOT NULL, \`channel_id\` char(36) NOT NULL, \`name\` varchar(512) NOT NULL, \`language\` varchar(10) NOT NULL, \`category\` varchar(50) NOT NULL, \`status\` varchar(50) NOT NULL DEFAULT 'pending', \`components\` json NOT NULL, \`external_id\` varchar(100) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_896b789d0ef71384510126cd53\` (\`channel_id\`, \`name\`, \`language\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`conversations\` (\`id\` char(36) NOT NULL, \`company_id\` char(36) NOT NULL, \`customer_id\` char(36) NOT NULL, \`channel_id\` char(36) NOT NULL, \`status\` varchar(50) NOT NULL DEFAULT 'open', \`priority\` varchar(50) NOT NULL DEFAULT 'low', \`assigned_member_id\` char(36) NULL, \`last_message_id\` char(36) NULL, \`last_message_at\` datetime NULL, \`last_inbound_at\` datetime NULL, \`last_outbound_at\` datetime NULL, \`closed_at\` datetime NULL, \`closed_by_member_id\` char(36) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, INDEX \`IDX_b33fd3154ab3d72c50eee25a5c\` (\`company_id\`, \`customer_id\`), INDEX \`IDX_1becffcd34d7da5adf479724bd\` (\`company_id\`, \`assigned_member_id\`, \`status\`), INDEX \`IDX_6c854d7345eb96587505a9bbc0\` (\`company_id\`, \`status\`, \`last_message_at\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`messages\` (\`id\` char(36) NOT NULL, \`company_id\` char(36) NOT NULL, \`conversation_id\` char(36) NOT NULL, \`direction\` varchar(50) NOT NULL, \`sender_type\` varchar(50) NOT NULL, \`sender_member_id\` char(36) NULL, \`sender_customer_id\` char(36) NULL, \`client_message_id\` varchar(64) NULL, \`type\` varchar(50) NOT NULL DEFAULT 'text', \`body\` text NULL, \`reply_to_message_id\` char(36) NULL, \`template_id\` char(36) NULL, \`external_id\` varchar(128) NULL, \`status\` varchar(50) NOT NULL DEFAULT 'pending', \`status_updated_at\` datetime NULL, \`error_code\` varchar(50) NULL, \`error_message\` varchar(500) NULL, \`sent_at\` datetime NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, INDEX \`IDX_1c4e25587c4a84b77b31e9c4b3\` (\`company_id\`, \`created_at\`), UNIQUE INDEX \`IDX_8e11547d02e309f79e8ecea269\` (\`conversation_id\`, \`client_message_id\`), UNIQUE INDEX \`IDX_53fe666fc41688e72cd69823ba\` (\`conversation_id\`, \`external_id\`), INDEX \`IDX_8584a1974e1ca95f4861d975ff\` (\`conversation_id\`, \`created_at\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tags\` (\`id\` char(36) NOT NULL, \`company_id\` char(36) NOT NULL, \`name\` varchar(50) NOT NULL, \`color\` varchar(7) NULL, UNIQUE INDEX \`IDX_c5b24cab932924d8e18b471f0b\` (\`company_id\`, \`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`message_status_events\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`message_id\` char(36) NOT NULL, \`status\` varchar(50) NOT NULL, \`occurred_at\` datetime NOT NULL, \`error_code\` varchar(50) NULL, \`raw_payload\` json NULL, INDEX \`IDX_03971b1b2c443509aa06dfd555\` (\`message_id\`, \`occurred_at\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`message_attachments\` (\`id\` char(36) NOT NULL, \`message_id\` char(36) NOT NULL, \`type\` varchar(50) NOT NULL, \`mime_type\` varchar(100) NOT NULL, \`file_name\` varchar(255) NULL, \`size_bytes\` bigint NULL, \`storage_url\` varchar(1024) NULL, \`external_media_id\` varchar(128) NULL, \`width\` int NULL, \`height\` int NULL, \`duration_ms\` int NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`customer_tags\` (\`customer_id\` char(36) NOT NULL, \`tag_id\` char(36) NOT NULL, INDEX \`IDX_489550d8317a3551c3b10a98f3\` (\`tag_id\`), PRIMARY KEY (\`customer_id\`, \`tag_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`customer_notes\` (\`id\` char(36) NOT NULL, \`customer_id\` char(36) NOT NULL, \`conversation_id\` char(36) NULL, \`author_member_id\` char(36) NOT NULL, \`body\` text NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`customer_identities\` (\`id\` char(36) NOT NULL, \`customer_id\` char(36) NOT NULL, \`channel_id\` char(36) NOT NULL, \`external_id\` varchar(100) NOT NULL, \`profile_name\` varchar(200) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_a2b6aa53ffd2abe671fbfb95d3\` (\`channel_id\`, \`external_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`custom_field_definitions\` (\`id\` char(36) NOT NULL, \`company_id\` char(36) NOT NULL, \`key\` varchar(64) NOT NULL, \`label\` varchar(100) NOT NULL, \`field_type\` varchar(50) NOT NULL, \`options\` json NULL, \`is_required\` tinyint NOT NULL DEFAULT 0, \`position\` int NOT NULL DEFAULT '0', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_8b86c4514f676ebdb7ee2e0c91\` (\`company_id\`, \`key\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`customer_custom_values\` (\`customer_id\` char(36) NOT NULL, \`field_id\` char(36) NOT NULL, \`value\` text NULL, \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`customer_id\`, \`field_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`conversation_reads\` (\`conversation_id\` char(36) NOT NULL, \`member_id\` char(36) NOT NULL, \`last_read_message_id\` char(36) NULL, \`last_read_at\` datetime NOT NULL, PRIMARY KEY (\`conversation_id\`, \`member_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`conversation_assignments\` (\`id\` char(36) NOT NULL, \`conversation_id\` char(36) NOT NULL, \`member_id\` char(36) NOT NULL, \`assigned_by_member_id\` char(36) NULL, \`reason\` varchar(50) NOT NULL DEFAULT 'auto', \`assigned_at\` datetime NOT NULL, \`unassigned_at\` datetime NULL, INDEX \`IDX_ce31809193c8edf549eef1d3dc\` (\`member_id\`, \`unassigned_at\`), INDEX \`IDX_b053c8edd1c0c02c03f84c478e\` (\`conversation_id\`, \`assigned_at\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`company_settings\` (\`company_id\` char(36) NOT NULL, \`auto_assign_enabled\` tinyint NOT NULL DEFAULT 1, \`auto_assign_max_open\` int NOT NULL DEFAULT '10', \`auto_assign_sticky\` tinyint NOT NULL DEFAULT 1, \`auto_assign_notify_supervisors\` tinyint NOT NULL DEFAULT 1, \`business_hours\` json NULL, \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`company_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`analyses\` (\`id\` char(36) NOT NULL, \`company_id\` char(36) NOT NULL, \`target\` varchar(50) NOT NULL, \`message_id\` char(36) NULL, \`conversation_id\` char(36) NOT NULL, \`type\` varchar(50) NOT NULL, \`model\` varchar(100) NULL, \`status\` varchar(50) NOT NULL DEFAULT 'pending', \`label\` varchar(100) NULL, \`confidence\` decimal(5,4) NULL, \`result\` json NULL, \`error\` varchar(500) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`completed_at\` datetime NULL, INDEX \`IDX_aa53d494667156276eb338f1e9\` (\`message_id\`, \`type\`), INDEX \`IDX_7b7b9679eea6bed91bb73d0c1e\` (\`conversation_id\`, \`type\`, \`created_at\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sentiment_results\` (\`analysis_id\` char(36) NOT NULL, \`label\` varchar(50) NOT NULL, \`score_positive\` decimal(5,4) NOT NULL DEFAULT '0.0000', \`score_neutral\` decimal(5,4) NOT NULL DEFAULT '0.0000', \`score_negative\` decimal(5,4) NOT NULL DEFAULT '0.0000', PRIMARY KEY (\`analysis_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`company_members\` ADD CONSTRAINT \`FK_e33a61fd560f6412d3ffb39f225\` FOREIGN KEY (\`company_id\`) REFERENCES \`companies\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company_members\` ADD CONSTRAINT \`FK_535b42b6c7557886fd1c44501e4\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD CONSTRAINT \`FK_c642fb845de2edcae46635863ab\` FOREIGN KEY (\`company_id\`) REFERENCES \`companies\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD CONSTRAINT \`FK_48d92c1f85371120f3482067c45\` FOREIGN KEY (\`recipient_member_id\`) REFERENCES \`company_members\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pipeline_stages\` ADD CONSTRAINT \`FK_f47785618cf4c805258790bdd7d\` FOREIGN KEY (\`company_id\`) REFERENCES \`companies\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customers\` ADD CONSTRAINT \`FK_f0e29920aaf871f3eddbea69f0d\` FOREIGN KEY (\`company_id\`) REFERENCES \`companies\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customers\` ADD CONSTRAINT \`FK_02468c405111686477e20334e5c\` FOREIGN KEY (\`pipeline_stage_id\`) REFERENCES \`pipeline_stages\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customers\` ADD CONSTRAINT \`FK_5be2976027fca2fc234489f6c4e\` FOREIGN KEY (\`owner_member_id\`) REFERENCES \`company_members\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`channels\` ADD CONSTRAINT \`FK_72a124fc0c72b78a15df98044d5\` FOREIGN KEY (\`company_id\`) REFERENCES \`companies\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`message_templates\` ADD CONSTRAINT \`FK_b757e2607c244e1c57c3c2245ea\` FOREIGN KEY (\`company_id\`) REFERENCES \`companies\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`message_templates\` ADD CONSTRAINT \`FK_9f65b0360834879cd946d7349d8\` FOREIGN KEY (\`channel_id\`) REFERENCES \`channels\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`conversations\` ADD CONSTRAINT \`FK_862ddf00e602bfc08a970f55ae0\` FOREIGN KEY (\`company_id\`) REFERENCES \`companies\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`conversations\` ADD CONSTRAINT \`FK_c9f0434c15cacf894e996f69088\` FOREIGN KEY (\`customer_id\`) REFERENCES \`customers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`conversations\` ADD CONSTRAINT \`FK_1a99838ee2e2e940ad98ed2e9d8\` FOREIGN KEY (\`channel_id\`) REFERENCES \`channels\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`conversations\` ADD CONSTRAINT \`FK_1b8c8a0a82915a4087f8e641437\` FOREIGN KEY (\`assigned_member_id\`) REFERENCES \`company_members\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`conversations\` ADD CONSTRAINT \`FK_a53679287450d522a3f700088e9\` FOREIGN KEY (\`last_message_id\`) REFERENCES \`messages\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`conversations\` ADD CONSTRAINT \`FK_de1b5ae5ddd9e6e14c04005791c\` FOREIGN KEY (\`closed_by_member_id\`) REFERENCES \`company_members\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD CONSTRAINT \`FK_d9aec86fce1cad2c11ef0c04f18\` FOREIGN KEY (\`company_id\`) REFERENCES \`companies\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD CONSTRAINT \`FK_3bc55a7c3f9ed54b520bb5cfe23\` FOREIGN KEY (\`conversation_id\`) REFERENCES \`conversations\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD CONSTRAINT \`FK_a5f6c7c292ce646cfca2728b322\` FOREIGN KEY (\`sender_member_id\`) REFERENCES \`company_members\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD CONSTRAINT \`FK_e2b95fd4bbf04302cb4d0168793\` FOREIGN KEY (\`sender_customer_id\`) REFERENCES \`customers\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD CONSTRAINT \`FK_7f87cbb925b1267778a7f4c5d67\` FOREIGN KEY (\`reply_to_message_id\`) REFERENCES \`messages\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD CONSTRAINT \`FK_f7b87b9df16052b1b08eae2423b\` FOREIGN KEY (\`template_id\`) REFERENCES \`message_templates\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tags\` ADD CONSTRAINT \`FK_4c5a582c03eda17de9206ead759\` FOREIGN KEY (\`company_id\`) REFERENCES \`companies\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`message_status_events\` ADD CONSTRAINT \`FK_19884b69d4123258c6ea6d3c53e\` FOREIGN KEY (\`message_id\`) REFERENCES \`messages\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`message_attachments\` ADD CONSTRAINT \`FK_bf65c3db8657cef6197b68b8c88\` FOREIGN KEY (\`message_id\`) REFERENCES \`messages\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customer_tags\` ADD CONSTRAINT \`FK_40fefeebc64ed8fe22bc3c18a1c\` FOREIGN KEY (\`customer_id\`) REFERENCES \`customers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customer_tags\` ADD CONSTRAINT \`FK_489550d8317a3551c3b10a98f3c\` FOREIGN KEY (\`tag_id\`) REFERENCES \`tags\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customer_notes\` ADD CONSTRAINT \`FK_b77784184daa7589018ac4e8402\` FOREIGN KEY (\`customer_id\`) REFERENCES \`customers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customer_notes\` ADD CONSTRAINT \`FK_0425cfbcdd9dc5253b78faf50f8\` FOREIGN KEY (\`conversation_id\`) REFERENCES \`conversations\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customer_notes\` ADD CONSTRAINT \`FK_fbd3b5a05faa330333df4849eb6\` FOREIGN KEY (\`author_member_id\`) REFERENCES \`company_members\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customer_identities\` ADD CONSTRAINT \`FK_f029c64f58346eb3bb3d760a97e\` FOREIGN KEY (\`customer_id\`) REFERENCES \`customers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customer_identities\` ADD CONSTRAINT \`FK_eca1deaa1424f6bc1ae886f4e06\` FOREIGN KEY (\`channel_id\`) REFERENCES \`channels\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`custom_field_definitions\` ADD CONSTRAINT \`FK_6a69383cfa8fa884140e1675347\` FOREIGN KEY (\`company_id\`) REFERENCES \`companies\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customer_custom_values\` ADD CONSTRAINT \`FK_1a00257e38e8dc973aae1c1cfb6\` FOREIGN KEY (\`customer_id\`) REFERENCES \`customers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customer_custom_values\` ADD CONSTRAINT \`FK_6f3b0eddb3b22db900edaa598f0\` FOREIGN KEY (\`field_id\`) REFERENCES \`custom_field_definitions\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`conversation_reads\` ADD CONSTRAINT \`FK_25d515c61b895dc8d16c4a74ca0\` FOREIGN KEY (\`conversation_id\`) REFERENCES \`conversations\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`conversation_reads\` ADD CONSTRAINT \`FK_fa549e3657377c1f34066af6094\` FOREIGN KEY (\`member_id\`) REFERENCES \`company_members\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`conversation_reads\` ADD CONSTRAINT \`FK_4f5f2c8b806f3a2f164eb9d22c1\` FOREIGN KEY (\`last_read_message_id\`) REFERENCES \`messages\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`conversation_assignments\` ADD CONSTRAINT \`FK_caf43c5a2d0014523418843ec5b\` FOREIGN KEY (\`conversation_id\`) REFERENCES \`conversations\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`conversation_assignments\` ADD CONSTRAINT \`FK_24d5503687a369c70b13b04ad09\` FOREIGN KEY (\`member_id\`) REFERENCES \`company_members\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`conversation_assignments\` ADD CONSTRAINT \`FK_624fe9271027dc57ea5bb0c9989\` FOREIGN KEY (\`assigned_by_member_id\`) REFERENCES \`company_members\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company_settings\` ADD CONSTRAINT \`FK_717089d5a18a8b594c0184663ae\` FOREIGN KEY (\`company_id\`) REFERENCES \`companies\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`analyses\` ADD CONSTRAINT \`FK_a121e6518a54be955b24676242d\` FOREIGN KEY (\`company_id\`) REFERENCES \`companies\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`analyses\` ADD CONSTRAINT \`FK_0cf2387e06d4146f47afc6b8d73\` FOREIGN KEY (\`message_id\`) REFERENCES \`messages\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`analyses\` ADD CONSTRAINT \`FK_c3e4a55b512302ead44ad3fd83d\` FOREIGN KEY (\`conversation_id\`) REFERENCES \`conversations\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sentiment_results\` ADD CONSTRAINT \`FK_bade5d034ed37c13dd4e2da6d29\` FOREIGN KEY (\`analysis_id\`) REFERENCES \`analyses\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`sentiment_results\` DROP FOREIGN KEY \`FK_bade5d034ed37c13dd4e2da6d29\``);
        await queryRunner.query(`ALTER TABLE \`analyses\` DROP FOREIGN KEY \`FK_c3e4a55b512302ead44ad3fd83d\``);
        await queryRunner.query(`ALTER TABLE \`analyses\` DROP FOREIGN KEY \`FK_0cf2387e06d4146f47afc6b8d73\``);
        await queryRunner.query(`ALTER TABLE \`analyses\` DROP FOREIGN KEY \`FK_a121e6518a54be955b24676242d\``);
        await queryRunner.query(`ALTER TABLE \`company_settings\` DROP FOREIGN KEY \`FK_717089d5a18a8b594c0184663ae\``);
        await queryRunner.query(`ALTER TABLE \`conversation_assignments\` DROP FOREIGN KEY \`FK_624fe9271027dc57ea5bb0c9989\``);
        await queryRunner.query(`ALTER TABLE \`conversation_assignments\` DROP FOREIGN KEY \`FK_24d5503687a369c70b13b04ad09\``);
        await queryRunner.query(`ALTER TABLE \`conversation_assignments\` DROP FOREIGN KEY \`FK_caf43c5a2d0014523418843ec5b\``);
        await queryRunner.query(`ALTER TABLE \`conversation_reads\` DROP FOREIGN KEY \`FK_4f5f2c8b806f3a2f164eb9d22c1\``);
        await queryRunner.query(`ALTER TABLE \`conversation_reads\` DROP FOREIGN KEY \`FK_fa549e3657377c1f34066af6094\``);
        await queryRunner.query(`ALTER TABLE \`conversation_reads\` DROP FOREIGN KEY \`FK_25d515c61b895dc8d16c4a74ca0\``);
        await queryRunner.query(`ALTER TABLE \`customer_custom_values\` DROP FOREIGN KEY \`FK_6f3b0eddb3b22db900edaa598f0\``);
        await queryRunner.query(`ALTER TABLE \`customer_custom_values\` DROP FOREIGN KEY \`FK_1a00257e38e8dc973aae1c1cfb6\``);
        await queryRunner.query(`ALTER TABLE \`custom_field_definitions\` DROP FOREIGN KEY \`FK_6a69383cfa8fa884140e1675347\``);
        await queryRunner.query(`ALTER TABLE \`customer_identities\` DROP FOREIGN KEY \`FK_eca1deaa1424f6bc1ae886f4e06\``);
        await queryRunner.query(`ALTER TABLE \`customer_identities\` DROP FOREIGN KEY \`FK_f029c64f58346eb3bb3d760a97e\``);
        await queryRunner.query(`ALTER TABLE \`customer_notes\` DROP FOREIGN KEY \`FK_fbd3b5a05faa330333df4849eb6\``);
        await queryRunner.query(`ALTER TABLE \`customer_notes\` DROP FOREIGN KEY \`FK_0425cfbcdd9dc5253b78faf50f8\``);
        await queryRunner.query(`ALTER TABLE \`customer_notes\` DROP FOREIGN KEY \`FK_b77784184daa7589018ac4e8402\``);
        await queryRunner.query(`ALTER TABLE \`customer_tags\` DROP FOREIGN KEY \`FK_489550d8317a3551c3b10a98f3c\``);
        await queryRunner.query(`ALTER TABLE \`customer_tags\` DROP FOREIGN KEY \`FK_40fefeebc64ed8fe22bc3c18a1c\``);
        await queryRunner.query(`ALTER TABLE \`message_attachments\` DROP FOREIGN KEY \`FK_bf65c3db8657cef6197b68b8c88\``);
        await queryRunner.query(`ALTER TABLE \`message_status_events\` DROP FOREIGN KEY \`FK_19884b69d4123258c6ea6d3c53e\``);
        await queryRunner.query(`ALTER TABLE \`tags\` DROP FOREIGN KEY \`FK_4c5a582c03eda17de9206ead759\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP FOREIGN KEY \`FK_f7b87b9df16052b1b08eae2423b\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP FOREIGN KEY \`FK_7f87cbb925b1267778a7f4c5d67\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP FOREIGN KEY \`FK_e2b95fd4bbf04302cb4d0168793\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP FOREIGN KEY \`FK_a5f6c7c292ce646cfca2728b322\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP FOREIGN KEY \`FK_3bc55a7c3f9ed54b520bb5cfe23\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP FOREIGN KEY \`FK_d9aec86fce1cad2c11ef0c04f18\``);
        await queryRunner.query(`ALTER TABLE \`conversations\` DROP FOREIGN KEY \`FK_de1b5ae5ddd9e6e14c04005791c\``);
        await queryRunner.query(`ALTER TABLE \`conversations\` DROP FOREIGN KEY \`FK_a53679287450d522a3f700088e9\``);
        await queryRunner.query(`ALTER TABLE \`conversations\` DROP FOREIGN KEY \`FK_1b8c8a0a82915a4087f8e641437\``);
        await queryRunner.query(`ALTER TABLE \`conversations\` DROP FOREIGN KEY \`FK_1a99838ee2e2e940ad98ed2e9d8\``);
        await queryRunner.query(`ALTER TABLE \`conversations\` DROP FOREIGN KEY \`FK_c9f0434c15cacf894e996f69088\``);
        await queryRunner.query(`ALTER TABLE \`conversations\` DROP FOREIGN KEY \`FK_862ddf00e602bfc08a970f55ae0\``);
        await queryRunner.query(`ALTER TABLE \`message_templates\` DROP FOREIGN KEY \`FK_9f65b0360834879cd946d7349d8\``);
        await queryRunner.query(`ALTER TABLE \`message_templates\` DROP FOREIGN KEY \`FK_b757e2607c244e1c57c3c2245ea\``);
        await queryRunner.query(`ALTER TABLE \`channels\` DROP FOREIGN KEY \`FK_72a124fc0c72b78a15df98044d5\``);
        await queryRunner.query(`ALTER TABLE \`customers\` DROP FOREIGN KEY \`FK_5be2976027fca2fc234489f6c4e\``);
        await queryRunner.query(`ALTER TABLE \`customers\` DROP FOREIGN KEY \`FK_02468c405111686477e20334e5c\``);
        await queryRunner.query(`ALTER TABLE \`customers\` DROP FOREIGN KEY \`FK_f0e29920aaf871f3eddbea69f0d\``);
        await queryRunner.query(`ALTER TABLE \`pipeline_stages\` DROP FOREIGN KEY \`FK_f47785618cf4c805258790bdd7d\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP FOREIGN KEY \`FK_48d92c1f85371120f3482067c45\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP FOREIGN KEY \`FK_c642fb845de2edcae46635863ab\``);
        await queryRunner.query(`ALTER TABLE \`company_members\` DROP FOREIGN KEY \`FK_535b42b6c7557886fd1c44501e4\``);
        await queryRunner.query(`ALTER TABLE \`company_members\` DROP FOREIGN KEY \`FK_e33a61fd560f6412d3ffb39f225\``);
        await queryRunner.query(`DROP TABLE \`sentiment_results\``);
        await queryRunner.query(`DROP INDEX \`IDX_7b7b9679eea6bed91bb73d0c1e\` ON \`analyses\``);
        await queryRunner.query(`DROP INDEX \`IDX_aa53d494667156276eb338f1e9\` ON \`analyses\``);
        await queryRunner.query(`DROP TABLE \`analyses\``);
        await queryRunner.query(`DROP TABLE \`company_settings\``);
        await queryRunner.query(`DROP INDEX \`IDX_b053c8edd1c0c02c03f84c478e\` ON \`conversation_assignments\``);
        await queryRunner.query(`DROP INDEX \`IDX_ce31809193c8edf549eef1d3dc\` ON \`conversation_assignments\``);
        await queryRunner.query(`DROP TABLE \`conversation_assignments\``);
        await queryRunner.query(`DROP TABLE \`conversation_reads\``);
        await queryRunner.query(`DROP TABLE \`customer_custom_values\``);
        await queryRunner.query(`DROP INDEX \`IDX_8b86c4514f676ebdb7ee2e0c91\` ON \`custom_field_definitions\``);
        await queryRunner.query(`DROP TABLE \`custom_field_definitions\``);
        await queryRunner.query(`DROP INDEX \`IDX_a2b6aa53ffd2abe671fbfb95d3\` ON \`customer_identities\``);
        await queryRunner.query(`DROP TABLE \`customer_identities\``);
        await queryRunner.query(`DROP TABLE \`customer_notes\``);
        await queryRunner.query(`DROP INDEX \`IDX_489550d8317a3551c3b10a98f3\` ON \`customer_tags\``);
        await queryRunner.query(`DROP TABLE \`customer_tags\``);
        await queryRunner.query(`DROP TABLE \`message_attachments\``);
        await queryRunner.query(`DROP INDEX \`IDX_03971b1b2c443509aa06dfd555\` ON \`message_status_events\``);
        await queryRunner.query(`DROP TABLE \`message_status_events\``);
        await queryRunner.query(`DROP INDEX \`IDX_c5b24cab932924d8e18b471f0b\` ON \`tags\``);
        await queryRunner.query(`DROP TABLE \`tags\``);
        await queryRunner.query(`DROP INDEX \`IDX_8584a1974e1ca95f4861d975ff\` ON \`messages\``);
        await queryRunner.query(`DROP INDEX \`IDX_53fe666fc41688e72cd69823ba\` ON \`messages\``);
        await queryRunner.query(`DROP INDEX \`IDX_8e11547d02e309f79e8ecea269\` ON \`messages\``);
        await queryRunner.query(`DROP INDEX \`IDX_1c4e25587c4a84b77b31e9c4b3\` ON \`messages\``);
        await queryRunner.query(`DROP TABLE \`messages\``);
        await queryRunner.query(`DROP INDEX \`IDX_6c854d7345eb96587505a9bbc0\` ON \`conversations\``);
        await queryRunner.query(`DROP INDEX \`IDX_1becffcd34d7da5adf479724bd\` ON \`conversations\``);
        await queryRunner.query(`DROP INDEX \`IDX_b33fd3154ab3d72c50eee25a5c\` ON \`conversations\``);
        await queryRunner.query(`DROP TABLE \`conversations\``);
        await queryRunner.query(`DROP INDEX \`IDX_896b789d0ef71384510126cd53\` ON \`message_templates\``);
        await queryRunner.query(`DROP TABLE \`message_templates\``);
        await queryRunner.query(`DROP INDEX \`IDX_20b3662df2548b1a2a120db326\` ON \`channels\``);
        await queryRunner.query(`DROP INDEX \`IDX_17f217069468737f98e5ce9508\` ON \`channels\``);
        await queryRunner.query(`DROP TABLE \`channels\``);
        await queryRunner.query(`DROP INDEX \`IDX_c7394e23cee3906898dc219c5c\` ON \`customers\``);
        await queryRunner.query(`DROP INDEX \`IDX_bce1c8e2cd87b249a640f87bbc\` ON \`customers\``);
        await queryRunner.query(`DROP INDEX \`IDX_9bf3490812e7d308b05f08cbd3\` ON \`customers\``);
        await queryRunner.query(`DROP TABLE \`customers\``);
        await queryRunner.query(`DROP INDEX \`IDX_6d96531b70c35c80186dc8531c\` ON \`pipeline_stages\``);
        await queryRunner.query(`DROP TABLE \`pipeline_stages\``);
        await queryRunner.query(`DROP INDEX \`IDX_5790f95902331e18e3a410d1db\` ON \`notifications\``);
        await queryRunner.query(`DROP TABLE \`notifications\``);
        await queryRunner.query(`DROP INDEX \`IDX_6e865dcafa308a5a7825d8de5c\` ON \`company_members\``);
        await queryRunner.query(`DROP INDEX \`IDX_7e141c8e7fcd537db28ec8d68d\` ON \`company_members\``);
        await queryRunner.query(`DROP TABLE \`company_members\``);
        await queryRunner.query(`DROP INDEX \`IDX_d0af6f5866201d5cb424767744\` ON \`companies\``);
        await queryRunner.query(`DROP TABLE \`companies\``);
        await queryRunner.query(`DROP INDEX \`IDX_17d1817f241f10a3dbafb169fd\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_fe0bb3f6520ee0469504521e71\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\` ON \`users\``);
        await queryRunner.query(`DROP TABLE \`users\``);
    }

}
